cosmos/evm

- CHANGELOG.md
- rpc/backend/tx_info.go
title. adds non EIP1559 txs support so `cast` works as expected.
originally https://github.com/cosmos/evm/pull/1 but the changes in base branch broke this
> fix: cast send --legacy support

- cmd/evmd/cmd/root.go
- evmd/config.go
This fixes the export option on the example app:
- The chain ID was not being passed to the example app, thus making the command fail
- This refactors the viper chain ID handling to commands and allow the chain to be passed on the export app
---
I have...
> Fix example app export

- local_node.sh
The current implementation in `local_node.sh` uses an incorrect JSON path to set the maximum gas limit for blocks in the genesis file. This results in the `max_gas` parameter remaining at the default value `-1` (unlimited) instead of being set to the intended value of `10000000`.
The script is using the path `.consensus_params["block"]["max_gas"]` which doesn't match the actual structure in the genesis.json file. The correct path should be `.consensus.params.block.max_gas`.
- Updated the jq command in `local_node.sh` to use the correct JSON path structure
- Changed from:
```bash
jq '.consensus_params["block"]["max_gas"]="10000000"' "$GENESIS" >"$TMP_GENESIS" && mv "$TMP_GENESIS" "$GENESIS"
```
- To:
```bash
jq '.consensus.params.block.max_gas="10000000"' "$GENESIS" >"$TMP_GENESIS" && mv …
```
> Fix: Correct JSON path for consensus max_gas setting

- tests/ibc/helper.go
- tests/ibc/ibc_middleware_test.go
- tests/ibc/v2_ibc_middleware_test.go
- testutil/ibc.go
This PR adds test coverage to verify that both **IBC v1** and **IBC v2** flows are working as expected in `ExampleChain`.
**Coverage**
| File Name | Coverage |
|-----------|----------|
| github.com/cosmos/evm/ibc/module.go | 100.0% |
| github.com/cosmos/evm/ibc/utils.go | 100.0% |
| github.com/cosmos/evm/tests/ibc/helper.go | 81.0% |
| github.com/cosmos/evm/testutil/ibc.go | 100.0% |
| github.com/cosmos/evm/x/erc20/ibc_middleware.go | 91.7% |
| github.com/cosmos/evm/x/erc20/keeper/ibc_callbacks.go | 87.9% |
| github.com/cosmos/evm/x/ibc/transfer/ibc_module.go | 100.0% |
| github.com/cosmos/evm/x/ibc/transfer/keeper/keeper.go | 100.0% |
| github.com/cosmos/evm/x/ibc/transfer/keeper/msg_server.go | 100.0% |
| github.com/cosmos/evm/x/ibc/transfer/module.go | 72.7% |
| …
> tests: add ibc test cases

- Makefile
solving the problem using different versions of glibc
when building one version on ubuntu and running another version on the server, it can lead to problems due to different versions of the glibc library.
> static link

- Makefile
Fixes the `Phony` target to properly look at build.
> chore: Remove comma from Makefile phony

- CHANGELOG.md
- x/feemarket/keeper/keeper.go
- x/feemarket/keeper/params.go
Removes the v1 params base fee from the x/feemarket module. 
This seems to be a legacy parameter which is no longer needed since the `Params` object holds this data now. Any chains still using this v1 base fee data would need to execute a migration via an upgrade handler to migrate to the supported path. I don't think we should include any upgrade code here since I'm not aware of anyone actually using this and it's pretty trivial to write on the case by case basis if someone realizes they are affected by this.
---
I have...
and please add your handle next to the items …
> refactor: Remove old params object from x/feemarket

- tests/ibc/v2_ibc_middleware_test.go
This PR adds test cases for handling native ERC20 coins in the IBC v2 middleware.
Previously, test cases were not written because native ERC20 coins had the prefix `erc20/`, which was incompatible with IBC v2 (see #61 for details).
Now that the prefix has been changed to `erc20:` through #92, this restriction no longer applies, and the relevant functionality can be tested properly.
Complements: #63 
---
I have...
I have...
> tests: add erc20 native coin test cases for ibc v2 middleware

- precompiles/common/abi_test.go
This PR increases the test coverage of `precompiles/common/abi.go`.
- Before: 36.8%
- After: 91.2%
**How to verify**
```bash
go test -coverpkg=./... -coverprofile=coverage.out -tags=test ./...
go tool cover -html=coverage.out -o coverage.html
```
Related to: #49 
---
I have...
I have...
> tests: increase test coverage for precompiles/common/abi.go

- contracts/solidity/precompiles/slashing/ISlashing.sol
- precompiles/slashing/ISlashing.sol
- precompiles/slashing/abi.json
- precompiles/slashing/query_test.go
- precompiles/slashing/types.go
- testutil/integration/os/network/setup.go
Modify types of SigningInfo and Params to sync with cosmos-sdk types
- Params.`MinSignedPerWindow`
- Params.`SlashFractionDoubleSign`
- Params.`SlashFractionDowntime`
- SigningInfo.`StartHeight`
- SigningInfo.`indexOffset`
- SigningInfo.`jailedUntil`
- SigningInfo.`missedBlocksCounter`
- Params.`SignedBlocksWindow`
- Params.`DowntimeJailDuration`
Closes: #133 
---
I have...
I have...
> fix(precompiles): sdk-incompatible types of slashing precompile

- client/debug/debug.go
- cmd/evmd/cmd/root.go
- cmd/evmd/config/config.go
- rpc/apis.go
- rpc/backend/backend_suite_test.go
- rpc/backend/chain_info_test.go
- rpc/backend/evm_query_client_test.go
- rpc/namespaces/ethereum/net/api.go
- server/config/config.go
- server/config/toml.go
- server/flags/flags.go
- server/start.go
- tests/solidity/suites/precompiles/hardhat.config.js
- tests/solidity/test-helper.js
- x/ibc/transfer/module.go
closes: #195
Consolidates EVM chain ID such that it only needs to be updated in `cmd/evmd/config/config.go` and that change propagates towards every component and sub-config.
> Consolidate EVM Chain ID

- Makefile
This PR updates the `test-unit-cover` Makefile target to exclude generated files and non-essential directories from the final coverage report. This ensures the coverage percentage more accurately reflects the test coverage of core logic.
- Filters out the following from `coverage.txt`:
- Generated files: `*.pb.go`, `*.pb.gw.go`, `*.pulsar.go`
- Test helpers and mocks: `/testutil/`, `/test_*.go`, `/mocks/`
- SDK integration or non-core modules: `/proto/`, `/cmd/`, `/client/`, `/x/*/module.go`, `/ibc/testing/`, `/scripts/`, `/version/`
- Documentation and Markdown: `*.md`
Including these files in the coverage report artificially deflates the coverage percentage and creates noise when tracking test effectiveness. By excluding them, we can focus coverage metrics on files that contain actual …
> tests: exclude generated and irrelevant files from coverage report

- precompiles/slashing/query.go
- precompiles/slashing/types.go
- tests/integration/precompiles/slashing/test_query.go
This PR fixes a bug where consensus addresses returned from `GetSigningInfo` and `GetSigningInfos` were incorrectly used in their bech32-encoded form.
Previously, the bech32 string (typically 52 characters long) was treated as if it were a raw 20-byte address, leading to invalid conversions and silent data loss. 
With this change, consensus addresses are now properly decoded from bech32 to their original 20-byte binary representation before any further processing.
Closes: #XXXX
---
I have...
if you only reviewed selected …
> fix(precompiles/slashing): decode bech32 consensus address before converting to bytes

- api/cosmos/evm/vm/v1/msg.go
- utils/eth/eth.go
Closes: #280
Closes: #XXXX
---
I have...
I have...
> fix: non-eip-155 tx panic when get signer

- evmd/precompiles.go
- precompiles/distribution/distribution.go
- precompiles/distribution/query.go
- precompiles/distribution/tx.go
- precompiles/distribution/types.go
- precompiles/distribution/types_test.go
- precompiles/gov/gov.go
- precompiles/gov/query.go
- precompiles/gov/tx.go
- precompiles/gov/types.go
- precompiles/gov/types_test.go
- precompiles/slashing/query.go
- precompiles/slashing/slashing.go
- precompiles/slashing/tx.go
- precompiles/slashing/types.go
- precompiles/slashing/types_test.go
- precompiles/staking/query.go
- precompiles/staking/staking.go
- precompiles/staking/tx.go
- precompiles/staking/types.go
- precompiles/staking/types_test.go
- tests/integration/precompiles/distribution/test_setup.go
- tests/integration/precompiles/distribution/test_utils.go
- tests/integration/precompiles/gov/test_setup.go
- tests/integration/precompiles/slashing/test_setup.go
- tests/integration/precompiles/staking/test_setup.go
uses address codecs in precompiles
closes: EVM-77
---
I have...
I have...
> fix: use address codecs in precompiles

- .github/workflows/lint.yml
- .github/workflows/solidity-test.yml
- .github/workflows/test.yml
these jobs are required but weren't firing because the event is `merge_group` not `pull_request`: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
---
I have...
I have...
> ci: add merge_group to ci jobs

- precompiles/gov/types.go
- precompiles/p256/p256.go
- rpc/backend/blocks.go
- rpc/backend/node_info.go
- rpc/namespaces/ethereum/eth/filters/filters.go
- tests/integration/precompiles/p256/test_integration.go
- tests/integration/precompiles/p256/test_p256.go
- tests/integration/precompiles/p256/test_setup.go
- tests/integration/rpc/backend/test_blocks.go
Addresses: [EVM-172](https://github.com/cosmos/evm/issues/172)
> We found in the rpc package that some calls made to Tendermint RPC are not handled properly. In specific, the eth_getLogs rpc call when providing a blockHash.
---
I have...
> fix: properly bubble up errors in BlockHash rpcs and fix flaky tests

- .github/workflows/lint.yml
- .github/workflows/solidity-test.yml
- .github/workflows/test.yml
Instance sizes chosen based on:
- Average historical runtime (how slow it is)
- How well the workflow scales with cores (whether it pins a subset of cores or scales linearly)
Should be merged after #369 and #373
> post-audit: add bigger depot runners to gh workflows

- local_node.sh
Local node script was broken after the precompile refactor in the audit changes, crashing with error:
```
$ ./local_node.sh -y
...
failed to validate genesis state: failed to unmarshal erc20 genesis state: unknown field "native_precompiles" in types.Params [cosmos/cosmos-sdk@v0.53.0/x/genutil/client/cli/gentx.go:96]
```
Review and confirm local script is working as intended. 
---
I have...
I have...
> fix: update new precompile stucture in local node script

- rpc/apis.go
- rpc/namespaces/ethereum/net/api.go
The `net.NewPublicAPI` refers the config through client context and there is no `evm-chain-id`, `PublicAPI.networkVersion` is always set default value.
Then the ethereum rpc method `net_version` always returns `262144`, so I fixed it to use server context.
Closes: #411 
---
I have...
> fix: net NewPublicAPI use server context also

- CHANGELOG.md
- rpc/namespaces/ethereum/eth/filters/api.go
- rpc/namespaces/ethereum/eth/filters/api_test.go
Closes: https://github.com/cosmos/evm/issues/451
---
I have...
> fix: cleanup unused cancel function in filter

- .github/workflows/lint.yml
Reverts the automatic fixing for markdown errors by the github actions bot in the lint workflow.
Linting rules are unchanged.
> revert auto-fix for markdown linting

- CHANGELOG.md
- evmd/precompiles.go
- evmd/tests/ibc/ics20_precompile_transfer_test.go
- evmd/tests/ibc/v2_ics20_precompile_transfer_test.go
- ibc/interfaces.go
- ibc/utils.go
- precompiles/bank/bank.go
- precompiles/common/interfaces.go
- precompiles/distribution/distribution.go
- precompiles/distribution/query.go
- precompiles/distribution/tx.go
- precompiles/erc20/erc20.go
- precompiles/gov/gov.go
- precompiles/gov/query.go
- precompiles/gov/tx.go
- precompiles/ics20/ics20.go
- precompiles/slashing/slashing.go
- precompiles/slashing/tx.go
- precompiles/staking/query.go
- precompiles/staking/staking.go
- precompiles/staking/tx.go
- precompiles/werc20/werc20.go
- tests/integration/precompiles/distribution/test_setup.go
- tests/integration/precompiles/distribution/test_utils.go
- tests/integration/precompiles/gov/test_setup.go
- tests/integration/precompiles/ics20/test_setup.go
- tests/integration/precompiles/slashing/test_setup.go
- tests/integration/precompiles/staking/test_setup.go
This commit refactors the precompile modules to rely on interfaces for their keeper dependencies instead of concrete implementations. This significantly improves the modularity and testability of the precompile system.
Previously, precompiles directly depended on specific keeper structs (e.g., `*stakingkeeper.Keeper`) and instantiated `MsgServer` or `Querier` implementations within their methods. This created tight coupling between the precompiles and the internal structure of other modules.
This change follows the dependency inversion principle, making the precompiles more robust, easier to maintain, and significantly simpler to unit-test with mocks.
- Define a set of keeper interfaces in precompiles/common/interfaces.go that specify the exact methods required by the precompiles.
- …
> refactor: decouple keeper using interface on precompile

- CHANGELOG.md
> chore: set up changelog properly post (v0.4.x)

- .github/workflows/system-test.yml
- Makefile
- evmd/upgrades.go
- tests/systemtests/Makefile
- tests/systemtests/upgrade_test.go
closes: STACK-1444
adds a systemtest that ensures the chain can execute an upgrade from v0.4.0 to main.
---
I have...
> test: v0.4.1 -> main upgrade test

- CHANGELOG.md
- mempool/mempool.go
closes: #460 
Not a breaking change - uses configs instead of the actual objects during initialization, with sensible defaults still provided.
> (chore):Simplify Mempool Config

- CHANGELOG.md
- rpc/backend/call_tx.go
- rpc/backend/sign_tx.go
Closes: https://github.com/cosmos/evm/pull/545
---
I have...
> chore: check if mempool is not nil before accepting nonce gap error tx

- evmd/go.mod
- evmd/go.sum
The replace directive for pebble is no longer necessary. The current go-ethereum version compiles fine.
Closes #573
> fix(evmd): remove pebble replace directive

- evmd/tests/integration/x_vm_test.go
I'm adding a benchmark.
Here are the results.
```
W/ Patch
BenchmarkGasEstimation-11    	   19078	     63496 ns/op
w/o patch
BenchmarkGasEstimation-11    	    1471	    793256 ns/op
```
> chore: Add benchmark

- CHANGELOG.md
- rpc/backend/blocks.go
At the moment, when calling TendermintBlockResultByNumber with height=0, an error is returned:
```
failed to fetch block result from Tendermint: failed to fetch block result from Tendermint 0: height must be greater than 0, but got 0
```
This PR replaces 0 with `nil`, making the Tendermint client happy.
This issue happens when trying to filter logs.
Fixes #488
> fix: CometBlockResultByNumber when height is 0

- evmd/cmd/evmd/cmd/root.go
> fix: add SetQueryGasLimit to baseapp options
